find_path(LIBGLOG_INCLUDE_DIR glog/logging.h)
find_library(LIBGLOG_LIBRARY libglog.a)

set(LIBGLOG_LIBRARIES ${LIBGLOG_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    LIBGLOG DEFAULT_MSG LIBGLOG_INCLUDE_DIR LIBGLOG_LIBRARIES)

mark_as_advanced(LIBGLOG_INCLUDE_DIR LIBGLOG_LIBRARIES LIBGLOG_FOUND)

if(LIBGLOG_FOUND AND NOT LIBGLOG_FIND_QUIETLY)
    message(STATUS "LIBGLOG: ${LIBGLOG_INCLUDE_DIR}")
endif()
